// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class TIOW_ACE_Mod {
		author = "Sabre One";
		name = "TIOW Offical ACE Compatability Mod";
		requiredAddons[] = {"TIOWSpaceMarines"};
		requiredVersion = 0.1;
		units[] = {};
		weapons[] = {};
		worlds[] = {};
	};
};
